import type { Product, ProductsResponse } from "../types/product";
import type { Order } from "../types/order";
const API_URL = import.meta.env.VITE_API_URL?.replace(/\/$/, "") ?? "";
const PRODUCTS_PATH = API_URL ? "/api/products" : "/api/shopify/products";
const ORDERS_PATH = API_URL ? "/api/orders" : "/api/shopify/orders";
export const apiConfigured = true;
type ApiErrorBody = { error?: string; detail?: string };
declare global { interface Window { shopify?: { idToken?: () => Promise<string>; scopes?: { query: () => Promise<{ granted: string[]; optional?: string[]; required?: string[] }>; request: (scopes: string[]) => Promise<{ result?: string; detail?: { granted?: string[] } }> } } } }
async function ensureShopifyScopes() { const scopesApi = window.shopify?.scopes; if (!scopesApi) return; const current = await scopesApi.query(); const requiredScopes = ["read_products", "read_inventory", "read_locations", "read_orders"]; const missing = requiredScopes.filter((scope) => !current.granted.includes(scope)); if (missing.length) await scopesApi.request(missing); }
async function request<T>(path: string, init?: RequestInit): Promise<T> { const headers = new Headers(init?.headers); headers.set("Content-Type", "application/json"); const response = await fetch(`${API_URL}${path}`, { ...init, headers }); if (!response.ok) { let detail = ""; try { const body = await response.json() as ApiErrorBody; detail = body.detail || body.error || ""; } catch {} throw new Error(detail || `API ${response.status}: ${response.statusText}`); } return response.json() as Promise<T>; }
const numberOrZero = (value: unknown) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; };
export function normalizeProduct(product: Product): Product { return { ...product, price: numberOrZero(product.price), compareAtPrice: product.compareAtPrice == null ? null : numberOrZero(product.compareAtPrice), variants: product.variants.map((variant) => ({ ...variant, price: numberOrZero(variant.price), quantity: numberOrZero(variant.quantity), weight: numberOrZero(variant.weight) })) }; }
export async function getProducts(): Promise<ProductsResponse> { await ensureShopifyScopes(); const data = await request<ProductsResponse>(PRODUCTS_PATH); return { ...data, nodes: data.nodes.map(normalizeProduct) }; }
export async function getOrders(): Promise<{ nodes: Order[]; count: number; source: string }> { await ensureShopifyScopes(); return request<{ nodes: Order[]; count: number; source: string }>(ORDERS_PATH); }
export async function getHealth(): Promise<{ status: string }> { return request<{ status: string }>(API_URL ? "/health" : "/api/shopify/products"); }
export async function adjustInventory(input: { inventoryItemId: string; locationId: string; delta: number; currentQuantity: number; reason: string }, clerkToken: string) { const shopifyToken = window.shopify?.idToken ? await window.shopify.idToken() : ""; if (!shopifyToken) throw new Error("Abre Jatis Mutis desde Shopify Admin para ajustar inventario."); return request<{ success: boolean; adjustment: unknown }>("/api/shopify/inventory", { method: "POST", headers: { "X-Shopify-ID-Token": shopifyToken, "X-Clerk-Token": clerkToken }, body: JSON.stringify(input) }); }
export async function getLocations() { await ensureShopifyScopes(); const shopifyToken = window.shopify?.idToken ? await window.shopify.idToken() : ""; if (!shopifyToken) throw new Error("Falta la sesión de Shopify."); return request<{ locations: Array<{ id: string; name: string; isActive: boolean }> }>("/api/shopify/locations", { headers: { "X-Shopify-ID-Token": shopifyToken } }); }
